name: protflow
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.7.2=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.14=h5eee18b_0
  - pip=24.0=py310h06a4308_0
  - python=3.10.14=h955ad1f_1
  - readline=8.2=h5eee18b_0
  - setuptools=69.5.1=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - tzdata=2024a=h04d1e81_0
  - wheel=0.43.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - aiohappyeyeballs==2.3.4
      - aiohttp==3.10.0
      - aiosignal==1.3.1
      - asttokens==2.4.1
      - async-timeout==4.0.3
      - attrs==23.2.0
      - biopython==1.84
      - biotite==0.41.2
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - click==8.1.7
      - comm==0.2.2
      - contextlib2==21.6.0
      - contourpy==1.2.1
      - cycler==0.12.1
      - debugpy==1.8.2
      - decorator==5.1.1
      - docker-pycreds==0.4.0
      - exceptiongroup==1.2.2
      - executing==2.0.1
      - fair-esm==2.0.0
      - filelock==3.13.1
      - fonttools==4.53.1
      - frozenlist==1.4.1
      - fsspec==2024.2.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - huggingface-hub==0.24.5
      - idna==3.4
      - ipykernel==6.29.5
      - ipython==8.26.0
      - ipywidgets==8.1.3
      - jedi==0.19.1
      - jinja2==3.1.3
      - joblib==1.4.2
      - jupyter-client==8.6.2
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.11
      - kiwisolver==1.4.5
      - lightning-utilities==0.11.6
      - markupsafe==2.1.5
      - matplotlib==3.9.1
      - matplotlib-inline==0.1.7
      - ml-collections==0.1.1
      - mpmath==1.3.0
      - msgpack==1.0.8
      - multidict==6.0.5
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - numpy==1.26.3
      - packaging==24.1
      - parso==0.8.4
      - pastel==0.2.1
      - pexpect==4.9.0
      - pillow==10.2.0
      - platformdirs==4.2.2
      - poethepoet==0.10.0
      - pot==0.9.4
      - prompt-toolkit==3.0.47
      - protobuf==5.27.3
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.18.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.3.3
      - pyyaml==6.0.1
      - pyzmq==26.0.3
      - regex==2024.7.24
      - requests==2.28.1
      - safetensors==0.4.3
      - scikit-learn==1.5.1
      - scipy==1.14.0
      - sentencepiece==0.2.0
      - sentry-sdk==2.12.0
      - setproctitle==1.3.3
      - six==1.16.0
      - smmap==5.0.1
      - stack-data==0.6.3
      - sympy==1.12
      - threadpoolctl==3.5.0
      - timm==1.0.8
      - tokenizers==0.19.1
      - tomlkit==0.13.0
      - torch==2.1.0+cu121
      - torchaudio==2.1.0+cu121
      - torchcde==0.2.5
      - torchdiffeq==0.2.4
      - torchdyn==1.0.6
      - torchmetrics==1.4.0.post0
      - torchsde==0.2.6
      - torchvision==0.16.0+cu121
      - tornado==6.4.1
      - tqdm==4.66.4
      - traitlets==5.14.3
      - trampoline==0.1.2
      - transformers==4.43.3
      - triton==2.1.0
      - typing-extensions==4.9.0
      - urllib3==1.26.13
      - wandb==0.17.5
      - wcwidth==0.2.13
      - widgetsnbextension==4.0.11
      - yarl==1.9.4
prefix: /home/kongzitai/mambaforge-pypy3/envs/protflow
